--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/phuongaz-pm-pl/AzEconomy
build-by-default: true
branches:
- main
projects:
  AzEconomy:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: 4.1.6
      - src: sof3/await-generator/await-generator
        version: ^3.4.3
      - src: ColinHDev/libAsyncEvent/libAsyncEvent
        version: ^2.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...
