name: AzEconomy
main: phuongaz\azeconomy\AzEconomy
version: 1.0.0
api: 5.0.0
author: Phuongaz
src-namespace-prefix: phuongaz\azeconomy

permissions:
    azeconomy.command:
        description: Allow use command
        default: true
    azeconomy.command.currencies:
        description: Allow use command money
        default: true
    azeconomy.command.set:
        description: Allow use command money set
        default: true
    azeconomy.command.give:
        description: Allow use command money add
        default: true
    azeconomy.command.take:
        description: Allow use command money remove
        default: true
    azeconomy.command.pay:
        description: Allow use command money pay
        default: true
    azeconomy.command.top:
        description: Allow use command money top
        default: true